# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rosetta
version:      0.33
version_from: lib/Rosetta.pm
installdirs:  site
requires:
    Locale::KeyedText:             0.06
    SQL::SyntaxModel:              0.38

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
