# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rosetta
version:      0.38
version_from: lib/Rosetta.pm
installdirs:  site
requires:
    Locale::KeyedText:             1.00
    SQL::Routine:                  0.48

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
