# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rosetta
version:      0.3
version_from: 
installdirs:  site
requires:
    Locale::KeyedText:             0.03
    SQL::SyntaxModel:              0.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
