#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rosetta
version:      0.21
version_from: 
installdirs:  site
requires:
    Locale::KeyedText:             0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
